version: "3.9"

services:
  m3u-flask:
    build: .
    container_name: m3u-flask
    network_mode: host       # 使用宿主机网络
    restart: unless-stopped
    volumes:
      - ./config:/iptv/config
      - ./output:/iptv/output
      - ./merge.py:/iptv/merge.py
